# Generated by Django 6.0.3 on 2026-04-10 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_companyuser_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('accountant', 'Accountant')], default='accountant', max_length=20),
        ),
    ]
