# Generated by Django 6.0.3 on 2026-04-01 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='alert_100_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='budget',
            name='alert_80_sent',
            field=models.BooleanField(default=False),
        ),
    ]
